console.log("================================");
console.log("       MEU APLICATIVO");
console.log("================================");
console.log("        ");
console.log("Nome: Gustavo Duarte Lopes");
console.log("Cidade: Schroeder");
console.log("Atividade de interesse: jogos");
console.log("Quero aprender: desenvolvimento de aplicativos ");
console.log("Área de interesse: tecnologia");
console.log("Mensagem: Estou evoluindo na programação! ");